// Generated by CoffeeScript 1.4.0
(function() {
  var PageMod, Request, Widget, self, tabs;

  Widget = require("widget").Widget;

  PageMod = require("sdk/page-mod").PageMod;

  Request = require("sdk/request").Request;

  self = require("sdk/self");

  tabs = require("sdk/tabs");

  exports.main = function() {
    var scripts;
    scripts = [self.data.url("lib/jquery.js"), self.data.url("lib/strftime-min.js"), self.data.url("lib/jquery.timeago.js"), self.data.url("ghcr.js")];
    new Widget({
      id: "ghcr",
      label: "GitHub Code Review",
      contentURL: "http://www.mozilla.org/favicon.ico"
    });
    return new PageMod({
      include: "https://github.com/*",
      contentScriptFile: scripts,
      contentStyleFile: [self.data.url("ghcr.css")],
      onAttach: function(worker) {
        var createRequest;
        worker.port.emit("init");
        createRequest = function(url, data, callMe) {
          return Request({
            url: url,
            content: data,
            onComplete: function(res) {
              return worker.port.emit(callMe, res.json || {});
            }
          });
        };
        worker.port.on("request:get", function(url, data, callMe) {
          return createRequest(url, data, callMe).get();
        });
        return worker.port.on("request:post", function(url, data, callMe) {
          return createRequest(url, data, callMe).post();
        });
      }
    });
  };

}).call(this);
